### ISSUE TITLE
Express application type

### ISSUE THREAD

**Issue by TheWillG** [ParallelTask/dinoloop#15]
Inside `src/api/dino.ts` the constructor is this:
```
constructor(app: Express, baseUri: string) {
        this.appContainer = AppContainer.create(app);
        this.appContainer.baseUri = baseUri;
        this.appContainer.routeNotFoundMiddleware = RouteNotFoundMiddleware;
    }
```
When correct me if I am wrong, but I believe it should be `app: express.Application`. Please see example here for importing Express into app..... https://dev.to/briandgls/using-typescript-with-express--e0k
It looks like with Typescript you can import via `import * as express from 'express'` and then when you create a new app it is of type `const app: express.Application = express();`

This would make dino.ts express type `express.Application` and not `Express`.

**Comment by ParallelTask** [comment]
please refer [this](https://stackoverflow.com/questions/35706164/typescript-import-as-vs-import-require) and [this](https://stackoverflow.com/questions/29596714/new-es6-syntax-for-importing-commonjs-amd-modules-i-e-import-foo-require)

> 2016 update: The TypeScript compiler at some point started allowing import as foo from 'legacy-module-foo' to get the default import of a legacy module in certain circumstances. This is a violation of the ES6 specification (§15.2.1.16, “The value "" indicates that the import request is for the target module’s namespace object.”).


> import * as creates an identifier that is a module object, emphasis on object. According to the ES6 spec, this object is never callable or newable - it only has properties. If you're trying to import a function or class, you should use

```
import * as express from 'express';
express(); // is violation since express should be namespace and not invokable function
```

**Comment by ParallelTask** [comment]
I guess we run into issues doing that, please find the image for reference

https://pasteboard.co/HuBMCOd.png

_error:_
> Module '"d:/GitHub Projects/dinoloop/examples/parse_api/node_modules/@types/express/index"' has no default export.

**Comment by TheWillG** [comment]
Still getting the same error on a different computer (Macbook Pro) when trying to run the parse_api example:
```
src/app/app.ts(18,21): error TS2345: Argument of type 'Express' is not assignable to parameter of type 'e.Express'.
  Types of property 'request' are incompatible.
    Type 'Request' is not assignable to type 'Request'. Two different types with this name exist, but they are unrelated.
      Types of property 'range' are incompatible.
        Type '(size: number, options?: RangeParser.Options) => RangeParser.Result | RangeParser.Ranges' is not assignable to type '(size: number, options?: RangeParser.Options) => RangeParser.Result | RangeParser.Ranges'. Two different types with this name exist, but they are unrelated.
          Type 'RangeParser.Result | RangeParser.Ranges' is not assignable to type 'RangeParser.Result | RangeParser.Ranges'. Two different types with this name exist, but they are unrelated.
            Type 'Result.invaild' is not assignable to type 'Result | Ranges'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dinoloop-parse-api-example@1.0.0 build: `npm run clean && tsc --p ./tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the dinoloop-parse-api-example@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qxv3902/.npm/_logs/2018-07-18T17_07_47_975Z-debug.log
```

**Comment by ParallelTask** [comment]
Hey! We will look into this issue once the v2 changes are ready :+1:

**Comment by ParallelTask** [comment]
@TheWillG I have modified `constructor(app: Express, baseUri: string)` to `constructor(app: any, baseUri: string)`, since dinoloop internal uses its own types. Try with the latest commit changes and let us know your comments. I think we can close this issue, if it solves your problem. Since it is typing issue. Adding `any` might fix it :+1:

**Comment by ParallelTask** [comment]
@TheWillG Please, can you confirm on this? is this issue still exists?

**Comment by TheWillG** [comment]
Yes, this has fixed the type issue
