### ISSUE TITLE
async Controller method supported?

### ISSUE THREAD

**Issue by spidgorny** [ParallelTask/dinoloop#37]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to have support for async controller functions.
```
	@HttpGet('/async')
	async async() {
		return {a: 'b'};
	}
```

Currently it returns an empty {} JSON.

**Describe alternatives you've considered**

Create an async service and use callback in the controller. Ugly.

**Additional context**
-

**Comment by spidgorny** [comment]
[@Async()](https://github.com/ParallelTask/dinoloop/blob/master/wiki/attributes.md#async) decorator is the solution. RTFM.

**Comment by ParallelTask** [comment]
@spidgorny Can we go ahead and close this issue?
