### ISSUE TITLE
Need to add custome decorators to Controllers and Api

### ISSUE THREAD

**Issue by gauravkul** [ParallelTask/dinoloop#38]
We started using dinoloop in our api server which has node.js & express. Choice of dinoloop was largely because of the fact that old code and registered routes could continue to work unaffected and new code could be written in dinoop controller and typescript. This worked great without any issue.

Now we need to  have requirement of custom validation done on each new routes (routes registered using dinoloop). Example Joi schema validation of the sent response. I want to define custom decorators for this purpose. I looked at the dinoloop source code for this purpose but couldn't find a way to do that.  

While adding the custom decorator I can store the target type constructor name , method name and data (joi schema) in my code but in any RequestEndMiddleware I have no way of knowing which controller target class and method name was used to execute this route.

Please let me know how can I achive my desired results.

Thanks 
Gaurav

**Comment by ParallelTask** [comment]
@gauravkul I am just curious about the model validation on the response? People usually do on the request object. correct? Do you really need model validation on the response object? since the response is already prepared by controller do we really need to reverify the model validation. Or is there something I am missing?

**Comment by ParallelTask** [comment]
> While adding the custom decorator I can store the target type constructor name , method name and data (joi schema) in my code

  Could you paste some snippet to get some background information on what you are trying to do

**Comment by ParallelTask** [comment]
The website was down yesterday due to dns it is up now. Let me know if you are able to find in docs
http://dinoloop.com/#/docs/intro

**Comment by gauravkul** [comment]
@ParallelTask  Thanks for Response.  Yes you are right in this regard that validation is generally done on the request object and dinoloop gives you the ability (decorators) to validate request body.

Problem in our case is that we have been using javascript (not typescript) and dynamodb for storing the user and application data. Since javascript is not typesafe and there is no schema in dynamo db , because of various bugs and development and obviously carelessness over the years , we end up having some of the response data which is non-standardise.  Our controller apis pick various fields from various table object to create the response data so it is not just a single field from particular table I am talking about.

For example custome.address is generally a array but in very few cases it is also present as a object.  Same is true for others nested level fields in other tables. Frontend android app ends up having lots ofcrash or other issues because of this non-standardise data. Real problem arises with some of the public apis which are exposed to 3rd party vendors and partners.

I know we should ideally do this validation while fetching the data from db but we dont have resources for that. Morever we ourselves dont know whether validation on all fields would be okay for old apis.
Thats why we thought of having response validation (joi) for some of the new api's written in typescript with dinoloop.

I think if you give the ability to add and customise the features and expose necessary information , that would be very helpful in its adoption.

Thanks.
Gaurav

**Comment by ParallelTask** [comment]
@gauravkul I am still curious about the real use case of having validation at response since the request is already processed. The only thing I can think of is if you get schema validation error in response object then maybe you are going to log it somewhere to fix it and send a 500 error to the client?

I just added the feature you requested in the latest version i.e. `v2.4.0`. You can now use  `@Returns()` decorator. The following example explains. I will update the docs when I get some time

    // sync version
    @Returns({ hello: '$world' })
    @HttpGet('/returns')
    getReturnsData(): string {
        return 'ReturnsData';
    }

    // async version
    @Async()
    @Returns(joiSchemaObject)
    @HttpGet('/returnsAsync')
    async getReturnsAsyncData(): Promise<string> {
        return await Deferrer.run<string>((resolve, reject) => {
            setTimeout(() => resolve('ReturnsAsyncData'), 10);
        });
    }

    // this is requestEndMiddleWare
    export class ResponseMiddleware extends RequestEndMiddleware {
        invoke(req: Request, res: Response, next: NextFunction, result: any, props?: IDinoRequestEndProps): void {
           // props are the new properties added in v2.4.0
           // props.returns contain the object that was added by the @Returns decorator
           // props.result also contain the result, you can still use **result: any** argument
          response.json({
             result: result,
             resultType: props.returns
          });
       }
     }
Let me know if this is what you are expecting.

**Comment by gauravkul** [comment]
@ParallelTask  Thanks a Lot. Yes we want to log that errors in prometheus-grafana monitoring and send non-200 response to client.

Let me test it and check.

Thanks Again.
Regards,
Gaurav

**Comment by ParallelTask** [comment]
@gauravkul If it works we will close the issue

**Comment by ParallelTask** [comment]
@gauravkul  Any update?

**Comment by gauravkul** [comment]
@ParallelTask  Sorry for the delay in confirmation. This corona virus has created a lot of mess in workplace. 
Yes this works perfectly. Thanks a ton. 
I very much like the idea of IDinoRequestEndProps which contains the result as well custom decorators objects field(s).
